// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:898e7642-36bd-4380-910f-4cb9f3e15eb0',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reactapp-hosting-mobilehub-1142032963',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dgdqzd08mpk4z.cloudfront.net',
    'aws_mobile_analytics_app_id': '7a1bc004ccaf4fc0829171a4b12a6134',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '26689608-d42f-4d81-83c5-013756c0b081',
    'aws_project_name': 'ReactApp-2019-09-15-16-51-25',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'reactapp-mobilehub-1142032963',
}

export default awsmobile;
